version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_DB=greencity
      - PGUSER=postgres
      - POSTGRES_PASSWORD=buRishRANsumeLiV
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
